export const paths = {
  page403: '/error/403',
  page404: '/error/404',
  page500: '/error/500',
  components: '/components',
  auth: {
    root: `/auth`,
    signIn: `/auth/sign-in`,
    signInPhone: `/auth/sign-in-phone`,
    signUp: `/auth/sign-up`,
  },
  dashboard: {
    root: '/',
    inventory: {
      root: '/ombor',
      analytics: '/ombor/analytics',
      plyonka: '/ombor/plyonka',
      plyonkaTransactions: (plyonkaId: string) => `/ombor/plyonka/${plyonkaId}/transaksiyalar`,
      kraska: '/ombor/kraska',
      kraskaTransactions: (kraskaId: string) => `/ombor/kraska/${kraskaId}/transaksiyalar`,
      suyuqKraska: '/ombor/suyuq-kraska',
      suyuqKraskaTransactions: (suyuqKraskaId: string) =>
        `/ombor/suyuq-kraska/${suyuqKraskaId}/transaksiyalar`,
      razvaritel: '/ombor/razvaritel',
      razvaritelTransactions: (razvaritelId: string) =>
        `/ombor/razvaritel/${razvaritelId}/transaksiyalar`,
      silindir: '/ombor/silindir',
      silindirTransactions: (silindirId: string) =>
        `/ombor/silindir/${silindirId}/transaksiyalar`,
      kley: '/ombor/kley',
      kleyTransactions: (kleyId: string) => `/ombor/kley/${kleyId}/transaksiyalar`,
      zapchastlar: '/ombor/zapchastlar',
      otxot: '/ombor/otxot',
      tayyorMahsulotlarTashkent: '/ombor/tayyor-mahsulotlar-tashkent',
      tayyorMahsulotlarAngren: '/ombor/tayyor-mahsulotlar-angren',
    },
    staff: {
      root: '/staff',
      crm: '/staff/crm',
      worker: '/staff/worker',
      accountant: '/staff/accountant',
      planner: '/staff/planner',
    },
    clients: {
      root: '/clients',
      detail: (clientId: string) => `/clients/${clientId}`,
      clients: '/clients',
      crm: '/clients/crm',
      agreementsClient: (clientId: string) => `/clients/agreements/${clientId}`,
      complaintsClient: (clientId: string) => `/clients/complaints/${clientId}`,
      transactionsClient: (clientId: string) => `/clients/transactions/${clientId}`,
      materials: '/clients/materials',
      materialsClient: (clientId: string) => `/clients/materials/${clientId}`,
      orderBook: '/clients/order-book',
    },
    stanok: {
      root: '/stanok',
      pechat: '/stanok/pechat',
      pechatProfile: (machineId: string) => `/stanok/pechat/${machineId}/profile`,
      reska: '/stanok/reska',
      laminatsiya: '/stanok/laminatsiya',
      brigadaPechat: (machineId: string) => `/stanok/pechat/${machineId}/brigada`,
      brigadaReska: (machineId: string) => `/stanok/reska/${machineId}/brigada`,
      brigadaLaminatsiya: (machineId: string) => `/stanok/laminatsiya/${machineId}/brigada`,
      materialsPechat: (machineId: string) => `/stanok/pechat/${machineId}/materials`,
      materialsReska: (machineId: string) => `/stanok/reska/${machineId}/materials`,
      materialsLaminatsiya: (machineId: string) => `/stanok/laminatsiya/${machineId}/materials`,
    },
    ishlabChiqarish: {
      root: '/ishlab-chiqarish',
      rejalashtirish: '/ishlab-chiqarish/rejalashtirish',
      nazorat: '/ishlab-chiqarish/nazorat',
      hisobotlar: '/ishlab-chiqarish/hisobotlar',
      uskunalar: '/ishlab-chiqarish/uskunalar',
    },
    buyurtmaPlanlashtirish: {
      root: '/buyurtma-planlashtirish',
    },
    finance: {
      root: '/finance',
      income: '/finance/income',
      expense: '/finance/expense',
      cash: {
        root: '/finance/cash',
        income: '/finance/cash/income',
        expense: '/finance/cash/expense',
      },
      transfer: {
        root: '/finance/transfer',
        income: '/finance/transfer/income',
        expense: '/finance/transfer/expense',
      },
    },
    reskaPanel: {
      root: '/reska-panel',
      overview: '/reska-panel/overview',
      queue: '/reska-panel/queue',
      reports: '/reska-panel/reports',
    },
    pechatPanel: {
      root: '/pechat-paneli',
      overview: '/pechat-paneli',
      inProgress: '/pechat-paneli/jarayonda',
      finished: '/pechat-paneli/yakunlangan',
      materials: '/pechat-paneli/materials',
    },
    laminatsiyaPanel: {
      root: '/laminatsiya-paneli',
      overview: '/laminatsiya-paneli',
    },
    user: {
      root: `/user`,
      list: `/user/list`,
    },
    games: {
      wordBattle: {
        root: '/word-battle',
        list: '/word-battle/list',
        create: '/word-battle/create',
        edit: (id: string) => `/word-battle/${id}/edit`,
        view: `/word-battle/:id/view`,
        users: `/word-battle/players`,
        settings: `/word-battle/settings`,
      },
      flashCard: {
        root: '/flash-card',
        list: '/flash-card/list',
        create: '/flash-card/create',
        categoryList: '/flash-card/category-list',
        edit: (id: string) => `/flash-card/${id}/edit`,
      },
      picsWord: {
        root: '/pics-word',
        create: '/pics-word/create',
        update: (id: string) => `/pics-word/${id}/update`,
        list: '/pics-word/list',
        settings: '/pics-word/settings',
      },
      oddOneOut: {
        root: '/odd-one-out',
        list: '/odd-one-out/list',
        create: '/odd-one-out/create',
        edit: (id: string) => `/odd-one-out/${id}/update`,
      },
    },
  },
};
